# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/fog-xml/all/fog-xml.rbi
#
# fog-xml-0.1.3

module Fog
end
module Fog::Xml
end
module Fog::XML
end
module Fog::Parsers
end
