# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/fog-json/all/fog-json.rbi
#
# fog-json-1.2.0

module Fog
end
module Fog::Json
end
module Fog::JSON
  def self.decode(obj); end
  def self.encode(obj); end
  def self.sanitize(data); end
end
class Fog::JSON::EncodeError < Fog::Errors::Error
end
class Fog::JSON::DecodeError < Fog::Errors::Error
end
