# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/govuk_publishing_components/all/govuk_publishing_components.rbi
#
# govuk_publishing_components-21.55.3

module GovukPublishingComponents
  def self.configure; end
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.render(component, options = nil); end
  def self.table_name_prefix; end
  def self.use_relative_model_naming?; end
end
module GovukPublishingComponents::Config
  def application_javascript; end
  def application_javascript=(obj); end
  def application_print_stylesheet; end
  def application_print_stylesheet=(obj); end
  def application_stylesheet; end
  def application_stylesheet=(obj); end
  def component_guide_title; end
  def component_guide_title=(obj); end
  def self.application_javascript; end
  def self.application_javascript=(obj); end
  def self.application_print_stylesheet; end
  def self.application_print_stylesheet=(obj); end
  def self.application_stylesheet; end
  def self.application_stylesheet=(obj); end
  def self.component_directory_name; end
  def self.component_guide_title; end
  def self.component_guide_title=(obj); end
  def self.gem_directory; end
end
class GovukPublishingComponents::Engine < Rails::Engine
end
module Anonymous_Module_626
end
module Anonymous_Module_627
end
module GovukPublishingComponents::Presenters
end
class GovukPublishingComponents::Presenters::SharedHelper
  def classes; end
  def get_heading_level; end
  def get_margin_bottom; end
  def get_margin_top; end
  def heading_level; end
  def initialize(local_assigns); end
  def margin_bottom; end
  def margin_top; end
  def options; end
end
class GovukPublishingComponents::Presenters::Attachment
  def alternative_format_contact_email; end
  def attachment_data; end
  def content_type; end
  def content_type_abbr; end
  def content_type_name; end
  def document?(*args, &block); end
  def file_size; end
  def initialize(attachment_data); end
  def is_official_document; end
  def number_of_pages; end
  def opendocument?(*args, &block); end
  def reference; end
  def spreadsheet?(*args, &block); end
  def title; end
  def unnumbered_reference; end
  def url; end
end
class GovukPublishingComponents::Presenters::Attachment::SupportedContentType
  def abbr; end
  def content_type; end
  def content_type_data; end
  def document?; end
  def initialize(content_type_data); end
  def name; end
  def opendocument?; end
  def self.find(content_type, extension = nil); end
  def spreadsheet?; end
end
class GovukPublishingComponents::Presenters::Attachment::UnsupportedContentType
  def abbr; end
  def content_type; end
  def document?; end
  def initialize(content_type:); end
  def name; end
  def opendocument?; end
  def spreadsheet?; end
end
class GovukPublishingComponents::Presenters::Breadcrumbs
  def breadcrumbs; end
  def initialize(breadcrumbs); end
  def item_list_element; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::Breadcrumb
  def [](*args, &block); end
  def aria_current; end
  def crumb; end
  def index; end
  def initialize(crumb, index); end
  def is_link?; end
  def item_list_element; end
  def list_item_item; end
  def path; end
  def tracking_data(breadcrumbs_length); end
  extend Forwardable
end
class GovukPublishingComponents::Presenters::BreadcrumbSelector
  def content_item; end
  def content_item_navigation; end
  def content_item_options; end
  def initialize(content_item, request, prioritise_taxon_breadcrumbs); end
  def options(navigation); end
  def output; end
  def parent_breadcrumbs; end
  def parent_item; end
  def parent_item_navigation; end
  def parent_item_options; end
  def prioritise_taxon_breadcrumbs; end
  def request; end
  def self.call(*args); end
end
class GovukPublishingComponents::Presenters::ButtonHelper
  def aria_label; end
  def button_type; end
  def classes; end
  def css_classes; end
  def data_attributes; end
  def destructive; end
  def href; end
  def html_options; end
  def info_text; end
  def info_text_classes; end
  def initialize(local_assigns); end
  def inline_layout; end
  def link?; end
  def margin_bottom; end
  def name; end
  def rel; end
  def secondary; end
  def secondary_quiet; end
  def start; end
  def target; end
  def text; end
  def title; end
  def type; end
  def value; end
end
class GovukPublishingComponents::Presenters::ContextualNavigation
  def breadcrumbs; end
  def breadcrumbs_based_on_parent; end
  def content_has_curated_related_items?; end
  def content_is_a_html_publication?; end
  def content_is_a_specialist_document?; end
  def content_is_tagged_to_a_live_taxon?; end
  def content_item; end
  def content_tagged_to_a_finder?; end
  def content_tagged_to_a_reasonable_number_of_step_by_steps?; end
  def content_tagged_to_current_step_by_step?; end
  def content_tagged_to_mainstream_browse_pages?; end
  def content_tagged_to_other_step_by_steps?; end
  def html_publication_with_parent?; end
  def initialize(content_item, request); end
  def parent_api_path; end
  def parent_finder; end
  def priority_breadcrumbs; end
  def query_parameters; end
  def request_path; end
  def show_brexit_cta?; end
  def simple_smart_answer?; end
  def step_by_step_count; end
  def step_nav_helper; end
  def tagged_to_brexit?; end
  def taxon_breadcrumbs; end
  def use_taxon_breadcrumbs?; end
end
class GovukPublishingComponents::Presenters::RelatedNavigationHelper
  def calculate_section_link_limit(links); end
  def construct_section_heading(section_title); end
  def content_item_details_for(key); end
  def content_item_links_for(key, only: nil); end
  def detailed_guide?; end
  def initialize(options = nil); end
  def related_contacts; end
  def related_document_collections; end
  def related_external_links; end
  def related_guides; end
  def related_items; end
  def related_legacy_topics; end
  def related_mainstream_content; end
  def related_navigation; end
  def related_navigation?; end
  def related_statistical_data_sets; end
  def related_taxons; end
  def related_topical_events; end
  def related_topics; end
  def related_world_locations; end
  def remaining_link_count(links); end
  def section_css_class(css_class, section_title, link = nil, link_is_inline = nil); end
  def section_data_track_count(section_title); end
  def section_heading_level; end
  def t_lang(content, options = nil); end
  def t_locale(content, options = nil); end
  def t_locale_check(locale); end
  def translation_present?(content); end
end
class GovukPublishingComponents::Presenters::StepByStepNavHelper
  def create_context(context); end
  def create_list_item_content(link); end
  def debug_missing_translation; end
  def debug_missing_translation=(obj); end
  def external_url?(href); end
  def generate_step_nav_id(step_title); end
  def get_list_element(style); end
  def get_list_style(style); end
  def link_active(active); end
  def link_href(active, href); end
  def link_text(active, text); end
  def link_with_step_nav_query_parameter(href); end
  def list(element); end
  def paragraph(text); end
  def render_step_nav_element(element, options); end
  def self.debug_missing_translation; end
  def self.debug_missing_translation=(obj); end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Context
  include ActionView::Helpers
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
end
class GovukPublishingComponents::Presenters::PageWithStepByStepNavigation
  def active_step_by_step; end
  def active_step_by_step?; end
  def active_step_nav_content_id; end
  def also_part_of_step_nav; end
  def configure_for_sidebar(step_nav_content); end
  def content_item; end
  def current_path; end
  def current_step_nav; end
  def format_related_links(step_by_step_navs); end
  def header; end
  def initialize(content_store_response, current_path, query_parameters = nil); end
  def parsed_related_to_step_navs; end
  def parsed_secondary_to_step_navs; end
  def parsed_step_navs; end
  def primary_step_by_steps?; end
  def related_links; end
  def related_to_step_navs; end
  def secondary_step_by_step; end
  def secondary_step_by_step?; end
  def secondary_step_by_steps; end
  def show_also_part_of_step_nav?; end
  def show_header?; end
  def show_related_links?; end
  def show_related_links_for_secondary_step_by_steps?; end
  def show_secondary_step_by_step?; end
  def show_sidebar?; end
  def sidebar; end
  def step_navs; end
  def step_navs_combined_list; end
  def steps; end
end
class GovukPublishingComponents::Presenters::StepByStepModel
  def base_path; end
  def content; end
  def content_id; end
  def content_item; end
  def initialize(content_item); end
  def steps; end
  def title; end
end
class GovukPublishingComponents::Presenters::ContentBreadcrumbsBasedOnParent
  def all_parents; end
  def breadcrumbs; end
  def content_item; end
  def initialize(content_item); end
end
class GovukPublishingComponents::Presenters::ContentBreadcrumbsBasedOnPriority
  def breadcrumbs; end
  def content_item; end
  def initialize(content_item); end
  def priority_taxon?(taxon); end
  def priority_taxons; end
  def self.call(content_item); end
  def taxon; end
  def taxon_tree(taxons); end
end
class GovukPublishingComponents::Presenters::ContentBreadcrumbsBasedOnTaxons
  def all_parents; end
  def breadcrumbs; end
  def content_item; end
  def initialize(content_item); end
end
class GovukPublishingComponents::Presenters::CheckboxesHelper
  def checkbox_markup(checkbox, index); end
  def css_classes; end
  def debug_missing_translation; end
  def debug_missing_translation=(obj); end
  def description; end
  def error; end
  def fieldset_describedby; end
  def has_conditional; end
  def has_exclusive; end
  def has_nested; end
  def heading_caption; end
  def heading_markup; end
  def heading_size; end
  def hint_text; end
  def id; end
  def initialize(options); end
  def items; end
  def list_classes; end
  def name; end
  def self.debug_missing_translation; end
  def self.debug_missing_translation=(obj); end
  def should_have_fieldset; end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Context
  include ActionView::Helpers
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
end
class GovukPublishingComponents::Presenters::SelectHelper
  def data_tracking?; end
  def get_options; end
  def initialize(options); end
  def option_markup; end
  def options; end
  def options_data_attribute(attributes); end
  def selected_option; end
end
class GovukPublishingComponents::Presenters::MetaTags
  def add_core_tags(meta_tags); end
  def add_organisation_tags(meta_tags); end
  def add_political_tags(meta_tags); end
  def add_step_by_step_tags(meta_tags); end
  def add_taxonomy_tags(meta_tags); end
  def content_item; end
  def details; end
  def has_content_history?; end
  def initialize(content_item, local_assigns, request); end
  def links; end
  def local_assigns; end
  def meta_tags; end
  def request; end
  def root_taxon_slugs(content_item); end
  def should_strip_dates_pii?(content_item, local_assigns); end
  def should_strip_postcode_pii?(content_item, local_assigns); end
end
class GovukPublishingComponents::Presenters::ContentItem
  def ==(other); end
  def as_taxonomy_sidebar_link; end
  def base_path; end
  def content_id; end
  def content_store_response; end
  def curated_taxonomy_sidebar_links; end
  def description; end
  def eql?(other); end
  def external_links; end
  def filter_link_type(links, type); end
  def hash; end
  def initialize(content_store_response); end
  def mainstream_browse_pages; end
  def parent; end
  def parent_taxon; end
  def parent_taxons; end
  def phase_is_live?(taxon); end
  def quick_links; end
  def related_collections; end
  def related_links; end
  def related_ordered_items; end
  def related_organisations; end
  def related_other_contacts; end
  def related_statistical_data_sets; end
  def related_topical_events; end
  def related_topics; end
  def related_world_locations; end
  def related_worldwide_organisations; end
  def taxon_links; end
  def title; end
end
class GovukPublishingComponents::Presenters::TranslationNavHelper
  def classes; end
  def has_translations?; end
  def initialize(local_assigns); end
  def inverse_class; end
  def margin_class; end
  def tracking_is_present?; end
  def translations; end
end
class GovukPublishingComponents::Presenters::SubscriptionLinksHelper
  def component_data_is_valid?; end
  def email_signup_link; end
  def email_signup_link_data_attributes; end
  def email_signup_link_text; end
  def feed_box_id; end
  def feed_link; end
  def feed_link_box_value; end
  def feed_link_data_attributes; end
  def feed_link_text; end
  def initialize(local_assigns); end
  def tracking_is_present?; end
end
class GovukPublishingComponents::Presenters::Page
  def attachments; end
  def base_path; end
  def body; end
  def canonical_url; end
  def content_item; end
  def description; end
  def document_type; end
  def has_image?; end
  def image_alt_text; end
  def image_placeholders; end
  def image_url; end
  def initialize(local_assigns); end
  def local_assigns; end
  def logo_url; end
  def requested_path; end
  def schema; end
  def title; end
end
class GovukPublishingComponents::Presenters::ArticleSchema
  def body; end
  def head_line; end
  def initialize(page); end
  def page; end
  def search_action; end
  def search_description; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::CreativeWorkSchema
  def about; end
  def author_schema; end
  def collection_pages(linked_type); end
  def document_collections; end
  def fetch_collection_pages(linked_type); end
  def has_part; end
  def image_schema; end
  def initialize(page); end
  def is_part_of; end
  def linked_page(step_by_step); end
  def linked_taxons; end
  def live_taxons; end
  def page; end
  def presenter; end
  def publishing_organisation; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::FaqPageSchema
  def answer_is_unset?(q_and_as, question); end
  def doc; end
  def initialize(page); end
  def main_entity; end
  def page; end
  def page_url; end
  def question_and_answers; end
  def question_element?(element); end
  def question_hash_is_unset?(q_and_as, question); end
  def questions_and_answers_markup; end
  def section_url(anchor); end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::GovernmentServiceSchema
  def initialize(page); end
  def page; end
  def provider; end
  def related_services; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::HasPartSchema
  def has_part_url; end
  def initialize(has_part_url); end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::HtmlPublicationSchema < GovukPublishingComponents::Presenters::FaqPageSchema
  def content_between(start_xpath, stop_xpath = nil); end
  def first_heading_type_with_more_than_one_occurance; end
  def heading_counts; end
  def heading_pairs; end
  def headings; end
  def initialize(page); end
  def less_than_two_headings_of_any_one_type?; end
  def page; end
  def pairs_hash(array); end
  def question_and_answers; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::IsPartOfSchema
  def initialize(is_part_of_url); end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::NewsArticleSchema
  def initialize(page); end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::OrganisationSchema
  def initialize(page); end
  def linked_org(url); end
  def members; end
  def minister_url(minister); end
  def ministers; end
  def ministers_with_grouped_roles; end
  def organisation_facet_params; end
  def page; end
  def parent_organisations; end
  def person_schema_for_minister(minister); end
  def related_organisations(link_type, schema_name); end
  def role_for_minister(minister); end
  def role_url(minister); end
  def search_action; end
  def search_description; end
  def slug; end
  def structured_data; end
  def sub_organisations; end
  def website_root; end
end
class GovukPublishingComponents::Presenters::PersonSchema
  def image_schema; end
  def initialize(page); end
  def page; end
  def presenter; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::PotentialSearchActionSchema
  def description; end
  def facet_params; end
  def initialize(facet_params, description); end
  def search_template; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::SearchResultsPageSchema
  def initialize(page); end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::DatasetSchema
  def description; end
  def distribution; end
  def initialize(page); end
  def name; end
  def page; end
  def present_attachment(attachment); end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::SchemaOrg
  def initialize(page); end
  def page; end
  def schema_for_page; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::HeadingHelper
  def classes; end
  def heading_tag; end
  def id; end
  def initialize(options); end
end
class GovukPublishingComponents::Presenters::ContentsListHelper
  def classes; end
  def contents; end
  def initialize(options); end
  def list_item_classes(list_item, nested); end
  def parent_modifier; end
  def wrap_numbers_with_spans(content_item_link); end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  include ActionView::Helpers::SanitizeHelper
end
class GovukPublishingComponents::Presenters::ImageCardHelper
  def context; end
  def debug_missing_translation; end
  def debug_missing_translation=(obj); end
  def description; end
  def extra_links; end
  def extra_links_no_indent; end
  def heading_text; end
  def href; end
  def href_data_attributes; end
  def image; end
  def initialize(local_assigns); end
  def is_tracking?; end
  def large; end
  def metadata; end
  def self.debug_missing_translation; end
  def self.debug_missing_translation=(obj); end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Context
  include ActionView::Helpers
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
end
class GovukPublishingComponents::Presenters::OrganisationLogoHelper
  def crest; end
  def debug_missing_translation; end
  def debug_missing_translation=(obj); end
  def image; end
  def initialize(local_assigns); end
  def logo_container_class; end
  def logo_content; end
  def logo_image_alt; end
  def logo_image_src; end
  def name; end
  def self.debug_missing_translation; end
  def self.debug_missing_translation=(obj); end
  def url; end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Context
  include ActionView::Helpers
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
end
class GovukPublishingComponents::Presenters::HighlightBoxesHelper
  def data_tracking?; end
  def initialize(options); end
end
class GovukPublishingComponents::Presenters::TaxonomyListHelper
  def image_card_data; end
  def initialize(image_cards); end
end
module GovukPublishingComponents::AppHelpers
end
class GovukPublishingComponents::AppHelpers::TaxonBreadcrumbs
  def all_parents; end
  def breadcrumbs; end
  def content_item; end
  def initialize(content_item); end
end
class GovukPublishingComponents::AppHelpers::TaxonBreadcrumbs::ContentItem
  def base_path; end
  def content_item; end
  def initialize(content_item); end
  def parent_taxon; end
  def phase_is_live?(taxon); end
  def title; end
end
class GovukPublishingComponents::AppHelpers::TableHelper
  def self.helper(context, caption = nil, opt = nil); end
end
class GovukPublishingComponents::AppHelpers::TableHelper::TableBuilder
  def body; end
  def cell(str, opt = nil); end
  def head; end
  def header(str, opt = nil); end
  def initialize(tag); end
  def row; end
  def tag; end
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::UrlHelper
end
class GovukPublishingComponents::AppHelpers::BrandHelper
  def border_color_class; end
  def brand_class; end
  def color_class; end
  def initialize(brand); end
end
class GovukPublishingComponents::AppHelpers::Environment
  def self.current_acceptance_environment; end
end
module GovukPublishingComponents::ApplicationHelper
end
class GovukPublishingComponents::ApplicationController < ActionController::Base
  def _layout(lookup_context, formats); end
  def self.__callbacks; end
  def self._helpers; end
  def self._routes; end
  def self._wrapper_options; end
  def self.helpers_path; end
  def self.middleware_stack; end
  def set_disable_slimmer_header; end
  def set_x_frame_options_header; end
  include ActionDispatch::Routing::UrlFor
  include Anonymous_Module_628
end
module Anonymous_Module_628
  def _generate_paths_by_default; end
  def _routes; end
  def self._routes; end
  def self.full_url_for(options); end
  def self.optimize_routes_generation?; end
  def self.polymorphic_path(record_or_hash_or_array, options = nil); end
  def self.polymorphic_url(record_or_hash_or_array, options = nil); end
  def self.route_for(name, *args); end
  def self.url_for(options); end
  def self.url_options; end
  extend ActiveSupport::Concern
  extend Anonymous_Module_626
  extend Anonymous_Module_627
  include ActionDispatch::Routing::UrlFor
  include Anonymous_Module_626
  include Anonymous_Module_627
end
class GovukPublishingComponents::ComponentGuideController < GovukPublishingComponents::ApplicationController
  def _layout(lookup_context, formats); end
  def component_breadcrumb(component_doc, component_example = nil); end
  def component_docs; end
  def component_has_js_file(component); end
  def component_has_sass_file(component, print_styles); end
  def components_in_use; end
  def components_in_use_docs; end
  def components_in_use_js; end
  def components_in_use_sass(print_styles); end
  def components_within_component(component); end
  def example; end
  def find_all_partials_in(components); end
  def find_partials_in(components); end
  def gem_component_docs; end
  def index; end
  def index_breadcrumb; end
  def preview; end
  def self._helpers; end
  def self._routes; end
  def self._wrapper_options; end
  def self.helpers_path; end
  def self.middleware_stack; end
  def show; end
  include ActionDispatch::Routing::UrlFor
  include Anonymous_Module_629
end
module Anonymous_Module_629
  def _generate_paths_by_default; end
  def _routes; end
  def self._routes; end
  def self.full_url_for(options); end
  def self.optimize_routes_generation?; end
  def self.polymorphic_path(record_or_hash_or_array, options = nil); end
  def self.polymorphic_url(record_or_hash_or_array, options = nil); end
  def self.route_for(name, *args); end
  def self.url_for(options); end
  def self.url_options; end
  extend ActiveSupport::Concern
  extend Anonymous_Module_626
  extend Anonymous_Module_627
  include ActionDispatch::Routing::UrlFor
  include Anonymous_Module_626
  include Anonymous_Module_627
end
class GovukPublishingComponents::ComponentDocs
  def all; end
  def app_documentation_directory; end
  def build(component); end
  def component_in_use(component); end
  def fetch_component_doc(id); end
  def fetch_component_docs; end
  def gem_documentation_directory; end
  def get(id); end
  def initialize(gem_components: nil, limit_to: nil); end
  def parse_documentation(file); end
  def used_in_this_app; end
end
class GovukPublishingComponents::ComponentDoc
  def accessibility_criteria; end
  def accessibility_excluded_rules; end
  def body; end
  def component; end
  def description; end
  def display_html?; end
  def display_preview?; end
  def embed; end
  def example; end
  def examples; end
  def github_search_url; end
  def govuk_frontend_components; end
  def html_accessibility_criteria; end
  def html_body; end
  def id; end
  def initialize(component); end
  def markdown_to_html(markdown); end
  def name; end
  def other_examples; end
  def partial_path; end
  def source; end
end
class GovukPublishingComponents::ComponentExample
  def block; end
  def contains_html?(input); end
  def context; end
  def dark_background?; end
  def data; end
  def data?; end
  def description; end
  def embed; end
  def has_block?; end
  def has_embed?; end
  def highlight_code(string_to_format = nil); end
  def html_description; end
  def html_safe_data; end
  def html_safe_strings(obj); end
  def id; end
  def initialize(id, example); end
  def markdown_to_html(markdown); end
  def name; end
  def pretty_data; end
  def right_to_left?; end
end
module GovukPublishingComponents::SharedAccessibilityCriteria
  def self.link; end
end
