# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mailcheck/all/mailcheck.rbi
#
# mailcheck-1.0.0

class Mailcheck
  def find_closest_domain(domain, domains); end
  def initialize(opts = nil); end
  def sift_3distance(s1, s2); end
  def split_email(email); end
  def suggest(email); end
end
