# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/plek/all/plek.rbi
#
# plek-3.0.0

class Plek
  def asset_root; end
  def asset_uri; end
  def defined_service_uri_for(service); end
  def env_var_or_dev_fallback(var_name, fallback_str = nil); end
  def external_domain; end
  def external_domain=(arg0); end
  def external_url_for(service, options = nil); end
  def find(service, options = nil); end
  def find_uri(*args); end
  def initialize(domain_to_use = nil, external_domain = nil); end
  def name_for(service); end
  def parent_domain; end
  def parent_domain=(arg0); end
  def public_asset_host; end
  def self.current(*arg0); end
  def self.find(*args); end
  def self.find_uri(*args); end
  def website_root; end
  def website_uri; end
end
class Plek::NoConfigurationError < StandardError
end
