# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/raindrops/all/raindrops.rbi
#
# raindrops-0.19.1

class Raindrops
  def [](arg0); end
  def []=(arg0, arg1); end
  def capa; end
  def decr(*arg0); end
  def evaporate!; end
  def incr(*arg0); end
  def initialize(arg0); end
  def initialize_copy(arg0); end
  def size; end
  def size=(arg0); end
  def to_ary; end
end
class Anonymous_Struct_646 < Struct
  def active; end
  def active=(_); end
  def queued; end
  def queued=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Raindrops::ListenStats < Anonymous_Struct_646
  def total; end
end
