# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/scss_lint-govuk/all/scss_lint-govuk.rbi
#
# scss_lint-govuk-0.2.0

module ScssLint
end
module ScssLint::Govuk
end
