# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/telephone_number/all/telephone_number.rbi
#
# telephone_number-1.4.7

module TelephoneNumber
  extend TelephoneNumber::ClassMethods
end
class Hash
  def deep_deep_merge!(other_hash, &block); end
  def deep_deep_merge(other_hash, &block); end
end
class TelephoneNumberValidator < ActiveModel::EachValidator
  def country(record); end
  def message; end
  def validate_each(record, attribute, value); end
end
module TelephoneNumber::ClassMethods
  def default_format_pattern; end
  def default_format_pattern=(format_string); end
  def default_format_string; end
  def default_format_string=(arg0); end
  def generate_override_file(file); end
  def invalid?(*args); end
  def override_file; end
  def override_file=(arg0); end
  def parse(number, country = nil); end
  def sanitize(input_number); end
  def valid?(number, country = nil, keys = nil); end
end
