inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - config/environments/production.rb
