# typed: strong
# This is an autogenerated file for Rails helpers.
# Please rerun bundle exec rake rails_rbi:helpers to regenerate.
module AddressHelper
  include Kernel
  include ActionView::Helpers
end

module AnswersHelper
  include Kernel
  include ActionView::Helpers
end

module ApplicationHelper
  include Kernel
  include ActionView::Helpers
end

module ErrorItemsHelper
  include Kernel
  include ActionView::Helpers
end

module FieldValidationHelper
  include Kernel
  include ActionView::Helpers
end

module FormFlowHelper
  include Kernel
  include ActionView::Helpers
end

module NhsNumberValidatorHelper
  include Kernel
  include ActionView::Helpers
end

module SchemaHelper
  include Kernel
  include ActionView::Helpers
end

module ActionController::Helpers
  sig { returns(T.all(AddressHelper, AnswersHelper, ApplicationHelper, ErrorItemsHelper, FieldValidationHelper, FormFlowHelper, NhsNumberValidatorHelper, SchemaHelper)) }
  def helpers; end
end
