# typed: strong
# This is an autogenerated file for Rails routes.
# Please run bundle exec rake rails_rbi:routes to regenerate.
class ActionController::Base
  include GeneratedUrlHelpers
end

module ActionView::Helpers
  include GeneratedUrlHelpers
end

class ActionMailer::Base
  include GeneratedUrlHelpers
end

module GeneratedUrlHelpers
  # Sigs for route /healthcheck(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def healthcheck_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def healthcheck_url(*args, **kwargs); end

  # Sigs for route /start(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def start_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def start_url(*args, **kwargs); end

  # Sigs for route /privacy(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def privacy_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def privacy_url(*args, **kwargs); end

  # Sigs for route /accessibility-statement(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def accessibility_statement_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def accessibility_statement_url(*args, **kwargs); end

  # Sigs for route /cookies(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def cookies_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def cookies_url(*args, **kwargs); end

  # Sigs for route /session-expired(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def session_expired_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def session_expired_url(*args, **kwargs); end

  # Sigs for route /live-in-england(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def live_in_england_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def live_in_england_url(*args, **kwargs); end

  # Sigs for route /nhs-letter(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def nhs_letter_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def nhs_letter_url(*args, **kwargs); end

  # Sigs for route /medical-conditions(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def medical_conditions_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def medical_conditions_url(*args, **kwargs); end

  # Sigs for route /name(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def name_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def name_url(*args, **kwargs); end

  # Sigs for route /date-of-birth(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def date_of_birth_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def date_of_birth_url(*args, **kwargs); end

  # Sigs for route /postcode-lookup(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def postcode_lookup_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def postcode_lookup_url(*args, **kwargs); end

  # Sigs for route /address-lookup(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def address_lookup_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def address_lookup_url(*args, **kwargs); end

  # Sigs for route /support-address(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def support_address_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def support_address_url(*args, **kwargs); end

  # Sigs for route /contact-details(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def contact_details_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def contact_details_url(*args, **kwargs); end

  # Sigs for route /check-contact-details(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_contact_details_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_contact_details_url(*args, **kwargs); end

  # Sigs for route /know-nhs-number(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def know_nhs_number_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def know_nhs_number_url(*args, **kwargs); end

  # Sigs for route /nhs-number(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def nhs_number_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def nhs_number_url(*args, **kwargs); end

  # Sigs for route /essential-supplies(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def essential_supplies_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def essential_supplies_url(*args, **kwargs); end

  # Sigs for route /dietary-requirements(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def dietary_requirements_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def dietary_requirements_url(*args, **kwargs); end

  # Sigs for route /carry-supplies(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def carry_supplies_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def carry_supplies_url(*args, **kwargs); end

  # Sigs for route /basic-care-needs(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def basic_care_needs_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def basic_care_needs_url(*args, **kwargs); end

  # Sigs for route /check-your-answers(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_your_answers_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_your_answers_url(*args, **kwargs); end

  # Sigs for route /confirmation(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def confirmation_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def confirmation_url(*args, **kwargs); end

  # Sigs for route /not-eligible-medical(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def not_eligible_medical_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def not_eligible_medical_url(*args, **kwargs); end

  # Sigs for route /not-eligible-england(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def not_eligible_england_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def not_eligible_england_url(*args, **kwargs); end
end
